import model from '@/content/model.json';
import type { NormalizedEvent } from '@/server/schema/event';
import { alert,groups,mean } from './common';
import type { Detector } from './types';
export function flowFeatures(e:NormalizedEvent){return [Math.log10(1+e.bytes_out),Math.log10(1+e.bytes_in),Math.log10(1+e.packets/Math.max(.1,e.duration_ms/1000)),Math.log10(1+e.bytes_out/Math.max(1,e.bytes_in)),Math.log10(1+e.duration_ms),(e.dst_port??0)/65535];}
export function predict(features:readonly number[]){const values=features.map(Math.fround);const result=model.classes.map(()=>0);for(const tree of model.trees){let index=0;let depth=0;while(tree[index].left>=0&&depth++<=6){const node=tree[index];index=values[node.feature]<=node.threshold?node.left:node.right;}tree[index].probability.forEach((p,i)=>result[i]+=p/model.trees.length);}return result;}
export function attackProbability(features:readonly number[]){return 1-predict(features)[model.benign_index];}
export function featureContributions(features:readonly number[]){const score=attackProbability(features);const deltas=features.map((_,i)=>{const changed=[...features];changed[i]=model.medians[i];return score-attackProbability(changed);});const total=deltas.reduce((s,v)=>s+Math.abs(v),0);return deltas.map((v,i)=>({feature:model.features[i],value:features[i],weight:total?v/total:0})).sort((a,b)=>Math.abs(b.weight)-Math.abs(a.weight));}
export const mlAnomaly:Detector=events=>groups(events,e=>e.src_ip).flatMap(g=>{const suspicious=g.filter(e=>attackProbability(flowFeatures(e))>=model.threshold);if(suspicious.length<3&&!suspicious.some(e=>e.bytes_out>=40_000_000))return [];const confidence=mean(suspicious.map(e=>attackProbability(flowFeatures(e))));const a=alert('ml_anomaly',suspicious,'medium',[{field:'model_probability',value:confidence,threshold:model.threshold},{field:'benchmark',value:model.benchmark},{field:'anomalous_flows',value:suspicious.length}],Math.min(.85,confidence));a.contributions=featureContributions(flowFeatures(suspicious[0]));return [a];});
